apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    tier: backend
spec:
  serviceAccountName: my-sa
      volumes:
        - name: mongodb-creds
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: mongodb-aws-secret
  replicas: 5
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: backend
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: private-registry/backend-app:1.0   
        ports:
        - containerPort: 8080
        volumeMounts:  
          - name: mongodb-creds
            monthPath: /tmp 
        envFrom:
         - configMapRef:
              name: backend-service-configmap
        resources:
          requests:
            cpu: 500m
            memory: 2000Mi 
