apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mongodb-aws-secret
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: "mongodb-creds"
          objectType: "secretsmanager"