apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-statefulset
  labels:
    tier: db
spec:
  replicas: 3
  selector:
    matchLabels:
      service: mongodb
  template:
    metadata:
      name: mongodb
      labels:
        service: mongodb
    spec:
      containers:
      - name: mongodb
        image: private-registry/mongodb-app:1.0   
        ports:
        - containerPort: 27017      
        volumeMounts:
          - name: mongo-volume
            mountPath: /data/db           
  volumeClaimTemplates:
    - metadata:
        name: mongo-volume
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi            
